name: ${name}
version: ${cht_version}
main: me.majhrs16.cht.spigot.ChatTranslatorPlugin
api-version: "1.16"
author: ${author}
description: ${description}

softdepend: [PlaceholderAPI]

commands:
  cht:
    description: ChatTranslator commands.
    usage: /cht <reload|lang|version>
    aliases: [chattranslator, ct]

permissions:
  cht.reload:
    description: Allows reloading the plugin configuration.
    default: op
  cht.lang:
    description: Allows changing your own chat language.
    default: true
  cht.lang.others:
    description: Allows changing another player's chat language.
    default: op
  cht.chat.color:
    description: Allows using colored chat when the server blocks it.
    default: true
  cht.signs.translate:
    description: Allows translating signs by interaction.
    default: true
