plugins {
    id 'java'
    id 'maven-publish'
}

group = 'me.majhrs16'
version = '2.1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation project(':src:core-api')
    implementation project(':src:textformatter')
    implementation project(':src:iflow')
    implementation project(':src:host')
    implementation 'net.kyori:adventure-text-minimessage:4.17.0'
    implementation 'net.kyori:adventure-api:4.17.0'
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'

    testImplementation project(':src:kernel')
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifactId = 'suite-inworld'
        }
    }
    repositories {
        maven {
            name = 'local'
            url = rootProject.layout.buildDirectory.dir('repo').get().asFile.toURI()
        }
    }
}