pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'textformatter-suite'

include 'src:core-api'
include 'src:kernel'
include 'src:iflow'
include 'src:host'
include 'src:textformatter'
include 'src:gtranslate'
include 'src:ltranslate'
include 'src:sync-http'
include 'src:sync-tcpudp'
include 'src:sync-discord'
include 'src:sync-telegram'
include 'src:sync-websocket'
include 'src:sync-velocity'
include 'src:observability'
include 'src:extension-api'
include 'src:example-extension'
include 'src:manager-api'
include 'src:manager-impl'
include 'src:presets'
include 'src:inworld'
include 'src:loadtest'
include 'src:spigot-host'
include 'src:common-legacy'
include 'src:transport'
include 'src:messages'
include 'src:tester'
include 'src:performance'
