plugins {
    id 'java'
    id 'maven-publish'
}

group = 'me.majhrs16'
version = '2.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifactId = 'suite-core-api'
        }
    }
    repositories {
        maven {
            name = 'local'
            url = rootProject.layout.buildDirectory.dir('repo').get().asFile.toURI()
        }
    }
}