plugins {
    id 'jacoco'
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

base {
    archivesName = 'textformatter-suite-spigot'
}

group = 'me.majhrs16'
version = '2.1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://repo.helpch.at/releases' }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {
    implementation 'me.majhrs16:suite-core-api:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-kernel:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-iflow:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-host:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-sync-discord:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-sync-http:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-sync-tcpudp:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-sync-telegram:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-gtranslate:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-ltranslate:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-messages:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-textformatter:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-tester:2.1.0-SNAPSHOT'
    implementation 'me.majhrs16:suite-transport:2.1.0-SNAPSHOT'

    implementation 'net.kyori:adventure-platform-bukkit:4.3.2'
    implementation 'net.kyori:adventure-text-minimessage:4.17.0'
    implementation 'net.kyori:adventure-api:4.17.0'
    implementation 'net.dv8tion:JDA:6.4.2'
    implementation 'org.yaml:snakeyaml:2.2'

    compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.6'

    testImplementation 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
    testImplementation 'me.clip:placeholderapi:2.11.6'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

test {
    useJUnitPlatform()
}

tasks.jar {
    archiveClassifier = 'thin'
}

shadowJar {
    archiveClassifier = ''
    archiveBaseName = 'textformatter-suite-spigot'
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

tasks.named('test') { finalizedBy 'jacocoTestReport' }
jacocoTestReport {
    dependsOn test
    reports { xml.required = true; html.required = true; csv.required = false }
}
