plugins {
    id 'java-library'
}

base {
    archivesName = 'chattranslator-common'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    api 'net.kyori:adventure-api:4.17.0'
    api 'net.kyori:adventure-text-minimessage:4.17.0'
    api 'net.kyori:adventure-text-serializer-plain:4.17.0'
    api 'net.kyori:adventure-text-serializer-gson:4.17.0'

    api 'org.yaml:snakeyaml:2.2'
    api 'org.springframework:spring-expression:5.3.33'

    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}