plugins {
    id 'java'
    id 'fabric-loom' version '1.10.5'
}

base {
    archivesName = 'chattranslator-fabric'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    implementation project(':common')
    include project(':common')

    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    include 'net.kyori:adventure-api:4.17.0'
    include 'net.kyori:adventure-text-minimessage:4.17.0'
    include 'net.kyori:adventure-text-serializer-plain:4.17.0'
    include 'net.kyori:adventure-text-serializer-gson:4.17.0'
    include 'org.yaml:snakeyaml:2.2'
    include 'org.springframework:spring-expression:5.3.33'
    include 'com.googlecode.json-simple:json-simple:1.1.1'
}

processResources {
    inputs.property 'version', rootProject.version
    filesMatching('fabric.mod.json') {
        expand version: rootProject.version
    }
}

loom {
    mixin {
        add sourceSets.main, 'chattranslator-refmap.json'
    }
}